### ISSUE TITLE
Screenshot Issue

### ISSUE THREAD

**Issue by hades1316** [swagkarna/Chuvi-Botnet#1]
Good day! I'm having problems executing the screenshot. I already installed the pyautogui. The backdoor is running on Windows OS and the server is on Linux. When I use the screenshot, it creates a blank file named "screenshot0" then the server.py disconnects from backdoor.py afterwards. Hoping for your kind response. Thanks.

**Comment by swagkarna** [comment]
wait for few days i am going to change entire code..and then u can try
